service: patients-registration
frameworkVersion: '2'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  listPatients:
    handler: handler.listPatients
    events:
      - httpApi: 'GET /patients'
  getPatient:
    handler: handler.getPatient
    events:
      - httpApi: 'GET /patients/{id}'

resources:
  Resources:
    PatientsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: patient
        AttributeDefinitions:
          - AttributeName: patient_id
            AttributeType: S
        KeySchema:
          - AttributeName: patient_id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1